//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dienstplan.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dienstplan.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add employee.
        /// </summary>
        public static string AddEmployee {
            get {
                return ResourceManager.GetString("AddEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add group.
        /// </summary>
        public static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        public static string Break {
            get {
                return ResourceManager.GetString("Break", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancle.
        /// </summary>
        public static string Cancle {
            get {
                return ResourceManager.GetString("Cancle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete employee.
        /// </summary>
        public static string DeleteEmployee {
            get {
                return ResourceManager.GetString("DeleteEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete group.
        /// </summary>
        public static string DeleteGroup {
            get {
                return ResourceManager.GetString("DeleteGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit employee.
        /// </summary>
        public static string EditEmployee {
            get {
                return ResourceManager.GetString("EditEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit employee:.
        /// </summary>
        public static string EditEmployee_ {
            get {
                return ResourceManager.GetString("EditEmployee:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit group.
        /// </summary>
        public static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit group:.
        /// </summary>
        public static string EditGroup_ {
            get {
                return ResourceManager.GetString("EditGroup:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employees.
        /// </summary>
        public static string Employees {
            get {
                return ResourceManager.GetString("Employees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name:.
        /// </summary>
        public static string FirstName_ {
            get {
                return ResourceManager.GetString("FirstName:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group:.
        /// </summary>
        public static string Group_ {
            get {
                return ResourceManager.GetString("Group:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to h.
        /// </summary>
        public static string h {
            get {
                return ResourceManager.GetString("h", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourse per week.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hourse per week:.
        /// </summary>
        public static string Hours_ {
            get {
                return ResourceManager.GetString("Hours:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan\h.
        /// </summary>
        public static string hPlanned {
            get {
                return ResourceManager.GetString("hPlanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name:.
        /// </summary>
        public static string LastName_ {
            get {
                return ResourceManager.GetString("LastName:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New employee:.
        /// </summary>
        public static string NewEmployee_ {
            get {
                return ResourceManager.GetString("NewEmployee:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New groupe:.
        /// </summary>
        public static string NewGroup_ {
            get {
                return ResourceManager.GetString("NewGroup:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okey.
        /// </summary>
        public static string Okey {
            get {
                return ResourceManager.GetString("Okey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OT.
        /// </summary>
        public static string OT {
            get {
                return ResourceManager.GetString("OT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roster.
        /// </summary>
        public static string Roster {
            get {
                return ResourceManager.GetString("Roster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select roster week:.
        /// </summary>
        public static string SelectRosterWeek {
            get {
                return ResourceManager.GetString("SelectRosterWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select week.
        /// </summary>
        public static string SelectWeek {
            get {
                return ResourceManager.GetString("SelectWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ∑ OT.
        /// </summary>
        public static string SOT {
            get {
                return ResourceManager.GetString("SOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TS.
        /// </summary>
        public static string TS {
            get {
                return ResourceManager.GetString("TS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type:.
        /// </summary>
        public static string Type_ {
            get {
                return ResourceManager.GetString("Type:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week from {0} to {1}.
        /// </summary>
        public static string WeekOf {
            get {
                return ResourceManager.GetString("WeekOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writting hours.
        /// </summary>
        public static string WrittingHours {
            get {
                return ResourceManager.GetString("WrittingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writting hours:.
        /// </summary>
        public static string WrittingHours_ {
            get {
                return ResourceManager.GetString("WrittingHours:", resourceCulture);
            }
        }
    }
}
